### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rjworks** [KCodeYT/GoGroups#6]
01:09:04.224 [GoMint Main Thread] ERROR io.gomint.server.Bootstrap - GoMint crashed:
java.lang.UnsupportedClassVersionError: de/kcodeyt/gogroups/GoGroups has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at io.gomint.server.plugin.PluginClassloader.loadClass0(PluginClassloader.java:95) ~[GoMint.jar:?]
        at io.gomint.server.plugin.PluginClassloader.loadClass(PluginClassloader.java:90) ~[GoMint.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at io.gomint.server.plugin.SimplePluginManager.constructAndInject(SimplePluginManager.java:362) ~[GoMint.jar:?]
        at io.gomint.server.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:284) ~[GoMint.jar:?]
        at io.gomint.server.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:170) ~[GoMint.jar:?]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:257) ~[GoMint.jar:?]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:86) [GoMint.jar:?]
01:09:04.280 [GoMint Main Thread] WARN  io.sentry.DefaultSentryClientFactory - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
01:09:04.284 [GoMint Main Thread] WARN  io.sentry.DefaultSentryClientFactory - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames

**Comment by rjworks** [comment]
java version 11
